### ISSUE TITLE
Error in login function

### ISSUE THREAD

**Issue by kovanovic** [JorrandeWit/ithenticate-api-python#1]
Hi,

I tried to use this api to connect to ithenticate but it doesn't work, I guess they changed somehting in the meantime. Here is the output:

```
(solar) vita@valinor 23:02:05 0 ~ > python ./test.py 
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    print(client.login())
  File "/media/data1/Dropbox/Work/projects/python-envs/solar/lib/python3.6/site-packages/iThenticate/API/Client.py", line 42, in login
    root = ET.fromstring(xml_string)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 238
```
This is a clean virtualenv with python 3.6.5 and only `ithenticate-api-python` installed.

**Comment by JorrandeWit** [comment]
Hi,

Thanks for the report. We are also experiencing problems on our platform with the ithenticate API. It has high priority to solve this, so please expect a fix within 48 hours.

Cheers,
Jorran

**Comment by JorrandeWit** [comment]
The problem you're reporting here seems to be related to an older version of the code that was on Github but not on PyPi (<0.7). This uncommitted code is now also pushed to Github.

Sorry for the confusion.

**Comment by kovanovic** [comment]
Hi, I've created a new virtual env and then installed ithenticate-api-python directly from GitHub: 
```
(solar) vita@valinor 20:37:53 1 ~ > pip install git+git://github.com/JorrandeWit/ithenticate-api-python.git
```
But the same exact error is happening.

**Comment by JorrandeWit** [comment]
I'm sorry. I've done the same thing: Create a clean virtualenv (Python 3.6), but all works fine here. Please make sure you have the right version (PyPi v0.7; this commit has been pushed to Github just 14 hours ago).

**Comment by kovanovic** [comment]
Hm... can it be due to my account being from the institution and not the "regular" account? 

I have the latest version installed directly from the GitHub on Python 3.6.5

**Comment by kovanovic** [comment]
Found what was the problem, the password was not escaped correctly, it contained & character in it (I used password generator). After I changed the password, it works!
